### ISSUE TITLE
Passare al ramo gh-pages

### ISSUE THREAD

**Issue by Mte90** [skillsAndMore/outerspace#1]
Utilizzare il ramo gh-pages invece del ramo master permette di utilizzare il web server id github ed i avere quindi una demo funzionante.

**Comment by EugenioPetulla** [comment]
Cavolo quanto hai ragione!! Ti voglio veramente bene ___

Preso in carico da me!

**Comment by Mte90** [comment]
https://www.youtube.com/watch?v=zGGpM-gP2wE basta che non arriviamo a questo punto

**Comment by EugenioPetulla** [comment]
No, tranquillo.

Comunque, Ramo creato: http://skillsandmore.github.io/outerspace

Chiudo, grazie ancora per la splendida idea!
